app/dashboard/tables/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.UserListView.as_view(), name='user_index'),
    path('create', views.user_create, name='user_create'),
    path('update/<int:pk>', views.user_edit, name='user_edit'),
    path('delete/<int:pk>', views.user_delete, name='user_delete'),
]

app/dashboard/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path, include
from dashboard import views
 

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile', views.profile, name='profile'),
    path('user',include('dashboard.tables.user.urls')),
    path('servers/<str:server>', views.servers, name='servers'),
]

app/monitoring/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect, render
from django.urls import reverse

def redirect_to_dashboard(request):
    return redirect(reverse('dashboard:index'))

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/auth/', include('dashboard_authentication.urls',namespace='dashboard_auth')),
    path('dashboard/', include('dashboard.urls',namespace='dashboard')),
    path('dashboard/drive/', include('storage_drive.urls',namespace='storage_drive')),
    path('api/dashboard/', include('dashboard_api.urls',namespace='dashboard_api')),
    path('', redirect_to_dashboard)
]

def page_not_found_view(request, exception):
    return render(request, 'dashboard/page-404.html', status=404)

handler404 = page_not_found_view

#if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/dashboard/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.urls import reverse

# Create your models here.
class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True,blank=True)
    address = models.CharField(max_length=100)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    email = models.EmailField("email", unique=True, blank=True)
    used_space = models.FloatField('used space', null=False, default=0)

class SystemData(models.Model):
    cpu_temp = models.FloatField()
    cpu_percent = models.FloatField()
    mem_percent = models.FloatField()
    disk_percent = models.FloatField()
    timestamp = models.IntegerField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"CPU: {self.cpu_percent}%, Memory: {self.mem_percent}%, Disk: {self.disk_percent}%, Timestamp: {self.timestamp}"

app/dashboard/tables/user/forms.py
from django import forms
from dashboard.models import CustomUser

class UserForm(forms.ModelForm):
    
    class Meta:
        model = CustomUser
        fields = [ 'username', 'email','age','address']

app/dashboard/tables/user/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, Http404
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect

from dashboard.context_processors import default_context
from dashboard.models import CustomUser
from .forms import *
import django_filters
from django_filters.views import FilterView 
import django_tables2 as tables

class UserFilter(django_filters.FilterSet):
    class Meta:
        model = CustomUser
        fields = ['id', 'username','email',]

class UserTable(tables.Table):
    actions = tables.TemplateColumn(
        '<div class="dropdown">'
            '<button class="btn btn-secondary dropdown-toggle" type="button" '
                'data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">'
                'Actions</button>'
                '<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">'
                    '<a class="dropdown-item edit-button" data-url="{% url \'dashboard:user_edit\' pk=record.pk %}">Edit</a>'
                    '<a class="">'
                    '<form method="post" action="{% url \'dashboard:user_delete\' pk=record.pk %}">'
                        '{% csrf_token %}'
                        '<button class=" delete-button dropdown-item" type="submit">Delete</button>'
                    '</form>'
                '</a>'
            '</div>'
        '</div>',
        verbose_name='Actions'
    )

    class Meta:
        model = CustomUser
        fields = ("id","username", "email", "address", "age","used_space", "date_joined" )
        attrs = {
            'class': 'table table-hover',
        }
        row_attrs = {
            "data-id": lambda record: record.pk
        }

class UserListView(LoginRequiredMixin, tables.SingleTableMixin, FilterView):
    model = CustomUser
    table_class = UserTable
    template_name = 'dashboard/tables/user/index.html'
    paginator_class = tables.LazyPaginator
    filterset_class = UserFilter
    #paginate_by = 1
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context = super().get_context_data()
        context.update(default_context())
        context.update({
            "form": UserForm(),
            'segment': 'user_index'
        })
        return context
    
    def get_queryset(self, *args, **kwargs):
        users = CustomUser.objects.all()
        return users

@login_required()
def user_create(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True})
    else:
        form = UserForm()
    return render(request, 'dashboard/tables/form_base.html', {'form': form})

@login_required()
def user_edit(request, pk):
    user = get_object_or_404(CustomUser, pk=pk)
    if request.method == 'POST':
        form = UserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True})
    else:
        form = UserForm(instance=user)
    return render(request, 'dashboard/tables/form_base.html', {'form': form, 'edit_url': reverse('dashboard:user_edit', kwargs={'pk': user.pk}) })



@login_required
def user_delete(request, pk):
    user = get_object_or_404(CustomUser, pk=pk)
    if request.method == 'POST':
        user.delete()
        return redirect('dashboard:user_index')
    raise Http404








# from django.contrib.auth.decorators import login_required
# from django.contrib.auth.mixins import LoginRequiredMixin
# from django.http import JsonResponse, Http404
# from django.shortcuts import render, get_object_or_404, redirect
# from django.utils.html import format_html
# from django.urls import reverse
# import django_tables2 as tables
# import django_filters
# from django_filters.views import FilterView 

app/dashboard/views.py
from django import template
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.template import loader
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from .models import *
import time, psutil
from dashboard_api.views import getStatData
from .context_processors import default_context

@login_required()
def index(request):
    context = default_context()
    context.update({'segment': 'dashboard:index'})
    html_template = loader.get_template('dashboard/index.html')
    return HttpResponse(html_template.render(context, request))

@login_required()
def profile(request):
    user = CustomUser.objects.get(id = request.user.id)
    context = default_context()
    context.update({'segment': 'dashboard:profile', 'user': user })
    html_template = loader.get_template('dashboard/profile.html')
    return HttpResponse(html_template.render(context, request))

@login_required()
def servers(request, server):
    context = default_context()
    if not server in context['servers']:
        raise Http404
    context.update({
        'segment': server,
        'server_stats_api_domain': context['servers'][server],
    })
    context.update(getStatData())
    return render(request, f'dashboard/servers/server-stats.html', context)

@login_required()
def pages(request):
    context = {}
    try:
        load_template = request.path.split('/')[-1]
        if load_template == 'admin':
            return HttpResponseRedirect(reverse('admin:index'))
        context['segment'] = load_template

        html_template = loader.get_template('dashboard/' + load_template)
        return HttpResponse(html_template.render(context, request))

    except template.TemplateDoesNotExist:

        html_template = loader.get_template('dashboard/page-404.html')
        return HttpResponse(html_template.render(context, request))

    except:
        html_template = loader.get_template('dashboard/page-500.html')
        return HttpResponse(html_template.render(context, request))

app/dashboard/templates/dashboard/tables/user/index.html
{% extends "layouts/base.html" %}

{% block stylesheets %}{% endblock stylesheets %}

{% block title %} Users {% endblock %}

{% load render_table from django_tables2 %}
{% block content %}

        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" /> -->
        <section class="pcoded-main-container">
            <div class="pcoded-wrapper">
    
                <div class="pcoded-content">
                    <div class="pcoded-inner-content">
                        <!-- [ breadcrumb ] start -->
                        <div class="page-header">
                            <div class="page-block">
                                <div class="row align-items-center">
                                    <div class="col-md-12">
                                        <div class="page-header-title">
                                            <h5 class="m-b-10">{{ _("Dashboard Tables") }}</h5>
                                        </div>
                                        <ul class="breadcrumb">
                                            <li class="breadcrumb-item"><a href="{% url 'dashboard:index' %}"><i class="feather icon-home"></i></a></li>
                                            <li class="breadcrumb-item"><a href="#!">{{ _("Tables") }}</a></li>
                                            <li class="breadcrumb-item"><a href="#">{{ _("Users") }}</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- [ breadcrumb ] end -->
                        <div class="main-body">
                            <div class="page-wrapper">
                                <div class="row">
                                    <div class="col-xl-12">
                                        <div class="card">
                                            <div class="card-header">
                                                <h5>{{ _("Users") }}</h5>
                                                <span class="d-block m-t-5"></span><button class="btn btn-primary create-button" data-toggle="modal" data-target="#dashboard-form-modal" data-url="{% url 'dashboard:user_create' %}">Create</button>
                                                {% if filterset %}
                                                    <form action="" method="get" class="form form-inline">
                                                        {{ filterset.form.as_p }}
                                                    </form>
                                                {% endif %}
                                            </div>
    
                                            <div class="card-block table-border-style">
                                                <div class="table-responsive">
                                                    {% render_table table  %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <div id="dashboard-form-modal" class="modal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">User</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form id="dashboard-form" action="{% url 'dashboard:user_create' %}">
                            {% csrf_token %}
                            {{ form.as_p }}
                        </form>
                        </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button id="save-button" type="button" class="btn btn-primary">Save changes</button>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}