app/dashboard/tables/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.UserListView.as_view(), name='user_index'),
    path('create', views.user_create, name='user_create'),
    path('update/<int:pk>', views.user_edit, name='user_edit'),
    path('delete/<int:pk>', views.user_delete, name='user_delete'),
]

app/dashboard/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path, include
from dashboard import views
 

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile', views.profile, name='profile'),
    path('user',include('dashboard.tables.user.urls')),
    path('servers/<str:server>', views.servers, name='servers'),
]

app/dashboard_authentication/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import login_view, register_user
from django.contrib.auth.views import LogoutView

app_name='dashboard_auth'

urlpatterns = [
     path('login', login_view, name="login"), 
     path('register', register_user, name="register"),
     path("logout", LogoutView.as_view(), name="logout"),
]

app/monitoring/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect, render
from django.urls import reverse

def redirect_to_dashboard(request):
    return redirect(reverse('dashboard:index'))

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/auth/', include('dashboard_authentication.urls',namespace='dashboard_auth')),
    path('dashboard/', include('dashboard.urls',namespace='dashboard')),
    path('dashboard/drive/', include('storage_drive.urls',namespace='storage_drive')),
    path('api/dashboard/', include('dashboard_api.urls',namespace='dashboard_api')),
    path('', redirect_to_dashboard)
]

def page_not_found_view(request, exception):
    return render(request, 'dashboard/page-404.html', status=404)

handler404 = page_not_found_view

#if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/storage_drive/urls.py
from django.urls import path
from . import views

app_name = 'storage_drive'

urlpatterns = [
    path('add/', views.file_create, name='add'),
    path('remove/', views.file_delete, name='remove'),
    path('list/', views.FileListView.as_view(), name='list'),
    path('<int:pk>/download/', views.FileDownloadView.as_view(), name='download'),
]

app/dashboard/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.urls import reverse

# Create your models here.
class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True,blank=True)
    address = models.CharField(max_length=100)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    email = models.EmailField("email", unique=True, blank=True)
    used_space = models.FloatField('used space', null=False, default=0)

class SystemData(models.Model):
    cpu_temp = models.FloatField()
    cpu_percent = models.FloatField()
    mem_percent = models.FloatField()
    disk_percent = models.FloatField()
    timestamp = models.IntegerField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"CPU: {self.cpu_percent}%, Memory: {self.mem_percent}%, Disk: {self.disk_percent}%, Timestamp: {self.timestamp}"

app/dashboard/tables/user/forms.py
from django import forms
from dashboard.models import CustomUser

class UserForm(forms.ModelForm):
    
    class Meta:
        model = CustomUser
        fields = [ 'username', 'email','age','address']

app/dashboard/tables/user/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, Http404
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect

from dashboard.context_processors import default_context
from dashboard.models import CustomUser
from .forms import *
import django_filters
from django_filters.views import FilterView 
import django_tables2 as tables

class UserFilter(django_filters.FilterSet):
    class Meta:
        model = CustomUser
        fields = ['id', 'username','email',]

class UserTable(tables.Table):
    actions = tables.TemplateColumn(
        '<div class="dropdown">'
            '<button class="btn btn-secondary dropdown-toggle" type="button" '
                'data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">'
                'Actions</button>'
                '<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">'
                    '<a class="dropdown-item edit-button" data-url="{% url \'dashboard:user_edit\' pk=record.pk %}">Edit</a>'
                    '<a class="">'
                    '<form method="post" action="{% url \'dashboard:user_delete\' pk=record.pk %}">'
                        '{% csrf_token %}'
                        '<button class=" delete-button dropdown-item" type="submit">Delete</button>'
                    '</form>'
                '</a>'
            '</div>'
        '</div>',
        verbose_name='Actions'
    )

    class Meta:
        model = CustomUser
        fields = ("id","username", "email", "address", "age","used_space", "date_joined" )
        attrs = {
            'class': 'table table-hover',
        }
        row_attrs = {
            "data-id": lambda record: record.pk
        }

class UserListView(LoginRequiredMixin, tables.SingleTableMixin, FilterView):
    model = CustomUser
    table_class = UserTable
    template_name = 'dashboard/tables/user/index.html'
    paginator_class = tables.LazyPaginator
    filterset_class = UserFilter
    #paginate_by = 1
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context = super().get_context_data()
        context.update(default_context())
        context.update({
            "form": UserForm(),
            'segment': 'user_index'
        })
        return context
    
    def get_queryset(self, *args, **kwargs):
        users = CustomUser.objects.all()
        return users

@login_required()
def user_create(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True})
    else:
        form = UserForm()
    return render(request, 'dashboard/tables/form_base.html', {'form': form})

@login_required()
def user_edit(request, pk):
    user = get_object_or_404(CustomUser, pk=pk)
    if request.method == 'POST':
        form = UserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True})
    else:
        form = UserForm(instance=user)
    return render(request, 'dashboard/tables/form_base.html', {'form': form, 'edit_url': reverse('dashboard:user_edit', kwargs={'pk': user.pk}) })



@login_required
def user_delete(request, pk):
    user = get_object_or_404(CustomUser, pk=pk)
    if request.method == 'POST':
        user.delete()
        return redirect('dashboard:user_index')
    raise Http404








# from django.contrib.auth.decorators import login_required
# from django.contrib.auth.mixins import LoginRequiredMixin
# from django.http import JsonResponse, Http404
# from django.shortcuts import render, get_object_or_404, redirect
# from django.utils.html import format_html
# from django.urls import reverse
# import django_tables2 as tables
# import django_filters
# from django_filters.views import FilterView 

app/dashboard/views.py
from django import template
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.template import loader
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from .models import *
import time, psutil
from dashboard_api.views import getStatData
from .context_processors import default_context

@login_required()
def index(request):
    context = default_context()
    context.update({'segment': 'dashboard:index'})
    html_template = loader.get_template('dashboard/index.html')
    return HttpResponse(html_template.render(context, request))

@login_required()
def profile(request):
    user = CustomUser.objects.get(id = request.user.id)
    context = default_context()
    context.update({'segment': 'dashboard:profile', 'user': user })
    html_template = loader.get_template('dashboard/profile.html')
    return HttpResponse(html_template.render(context, request))

@login_required()
def servers(request, server):
    context = default_context()
    if not server in context['servers']:
        raise Http404
    context.update({
        'segment': server,
        'server_stats_api_domain': context['servers'][server],
    })
    context.update(getStatData())
    return render(request, f'dashboard/servers/server-stats.html', context)

@login_required()
def pages(request):
    context = {}
    try:
        load_template = request.path.split('/')[-1]
        if load_template == 'admin':
            return HttpResponseRedirect(reverse('admin:index'))
        context['segment'] = load_template

        html_template = loader.get_template('dashboard/' + load_template)
        return HttpResponse(html_template.render(context, request))

    except template.TemplateDoesNotExist:

        html_template = loader.get_template('dashboard/page-404.html')
        return HttpResponse(html_template.render(context, request))

    except:
        html_template = loader.get_template('dashboard/page-500.html')
        return HttpResponse(html_template.render(context, request))

app/dashboard/templates/includes/navigation.html
<!-- [ Header ] start -->
<header class="navbar pcoded-header navbar-expand-lg navbar-light">
    <div class="m-header">
        <a class="mobile-menu" id="mobile-collapse1" href="javascript:"><span></span></a>
        <a href="/" class="b-brand">
            <div class="b-bg">
                <i class="feather icon-trending-up"></i>
            </div>
            <span class="b-title">{{ _("Dashboard") }}</span>
        </a>
    </div>
    <a class="mobile-menu" id="mobile-header" href="javascript:">
        <i class="feather icon-more-horizontal"></i>
    </a>
    <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
            <li><a href="javascript:" class="full-screen" onclick="javascript:toggleFullScreen()"><i
                    class="feather icon-maximize"></i></a></li>
            <!-- <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="javascript:" data-toggle="dropdown">Actions</a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="javascript:">Action 1</a></li>
                    <li><a class="dropdown-item" href="javascript:">Another action</a></li>
                    <li><a class="dropdown-item" href="javascript:">Something else here</a></li>
                </ul>
            </li> -->
            <li class="nav-item">
                <div class="main-search">
                    <div class="input-group">
                        <input type="text" id="m-search" class="form-control" placeholder="{{ _("Search") }} . . .">
                        <a href="javascript:" class="input-group-append search-close">
                            <i class="feather icon-x input-group-text"></i>
                        </a>
                        <span class="input-group-append search-btn btn btn-primary">
                                <i class="feather icon-search input-group-text"></i>
                            </span>
                    </div>
                </div>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li>
                <label>
                    <i class="icon feather icon-sun" id="theme-indicator"></i>
                    <input type="checkbox" id="theme-switch" class="d-none">
                </label>
            </li>
            <!-- <li>
                <div class="dropdown">
                    <a class="dropdown-toggle" href="javascript:" data-toggle="dropdown"><i
                            class="icon feather icon-bell"></i></a>
                    <div class="dropdown-menu dropdown-menu-right notification">
                        <div class="noti-head">
                            <h6 class="d-inline-block m-b-0">{{ _("Notifications") }}</h6>
                            <div class="float-right">
                                <a href="javascript:" class="m-r-10">mark as read</a>
                                <a href="javascript:">clear all</a>
                            </div>
                        </div>
                        <ul class="noti-body">
                            <li class="n-title">
                                <p class="m-b-0">NEW</p>
                            </li>
                            <li class="notification">
                                <div class="media">
                                    <img class="img-radius" src="{{ ASSETS_ROOT }}/images/user/avatar-1.jpg"
                                         alt="Generic placeholder image">
                                    <div class="media-body">
                                        <p><strong>{{ request.user.username }}</strong><span class="n-time text-muted"><i
                                                class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                                        <p>New ticket Added</p>
                                    </div>
                                </div>
                            </li>
                            <li class="n-title">
                                <p class="m-b-0">EARLIER</p>
                            </li>
                            <li class="notification">
                                <div class="media">
                                    <img class="img-radius" src="{{ ASSETS_ROOT }}/images/user/avatar-2.jpg"
                                         alt="Generic placeholder image">
                                    <div class="media-body">
                                        <p><strong>Joseph William</strong><span class="n-time text-muted"><i
                                                class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                                        <p>Prchace New Theme and make payment</p>
                                    </div>
                                </div>
                            </li>
                            <li class="notification">
                                <div class="media">
                                    <img class="img-radius" src="{{ ASSETS_ROOT }}/images/user/avatar-3.jpg"
                                         alt="Generic placeholder image">
                                    <div class="media-body">
                                        <p><strong>Sara Soudein</strong><span class="n-time text-muted"><i
                                                class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                                        <p>currently login</p>
                                    </div>
                                </div>
                            </li>
                        </ul>
                        <div class="noti-footer">
                            <a href="javascript:">show all</a>
                        </div>
                    </div>
                </div>
            </li> -->
            <li>
                <div class="dropdown drp-user">
                    <a href="javascript:" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon feather icon-settings"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right profile-notification">
                        <div class="pro-head">
                            <!-- <img src="{{ ASSETS_ROOT }}/images/user/avatar-1.jpg" class="img-radius" alt="User-Profile-Image"> -->
                            <span>
                                {{ request.user.username }}    
                            </span>
                            <a href="/auth-signin.html" class="dud-logout" title="Logout">
                                <i class="feather icon-log-out"></i>
                            </a>
                        </div>
                        <ul class="pro-body">
                            <li><a href="{% url 'dashboard:profile' %}" class="dropdown-item"><i class="feather icon-user"></i>
                                {{ _("Profile") }}</a></li>
                            <li><a href="{% url 'dashboard_auth:logout' %}" class="dropdown-item">
                                <i class="feather icon-lock"></i> {{ _("Logout") }}</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</header>
<!-- [ Header ] end -->

app/dashboard/templates/includes/scripts.html
<script src="/static/assets/js/vendor-all.min.js"></script>
<script src="/static/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/static/assets/js/pcoded.min.js"></script>
<script src="/static/assets/js/dark-mode.js"></script>
<script>
    $(document).ready(function(){
        var modal = $('#dashboard-form-modal');
        var saveButton = $('#save-button'),
            saveEditButton = $("#save-edit-button");
        saveButton.click(function() {
          const form = $('#dashboard-form')
          var url = form.attr('action');
          var data = form.serialize();
          var data = new FormData(document.getElementById('dashboard-form'));
          $.ajax({
            type: 'POST',
            url,
            processData: false,
            contentType: false,
            data,
            success: (response) => {
              console.log(response)
              if ((response.success)) {
                modal.modal('hide');
                location.reload();
              }
            },
            error: (response) =>{
              form.html(response.responseText);
            }
          } );
        });
        $('.edit-button').click(function(){
          openEditModalProf(this)
        })
        openEditModalProf = (el) => {
            
            const loadUrl = $(el).data('load-url')
            const url = $(el).data('url')
            //var url = form.attr('item-id');
            $.get(loadUrl || url, {}, (response) => {
              if (response) {
                modal.find('.modal-body').html(response)
                modal.modal('show');
              } else {
                
                form.html(response);
              }
            } );
          }
        saveEditButton.click(function() {
          const form = $('#dashboard-form')
          var url = form.attr('action');
          var data = new FormData(document.getElementById('dashboard-form'));
          $.ajax({
            type: 'POST',
            url,
            processData: false,
            contentType: false,
            data,
            success: (response) => {
              if ((response.success)) {
                modal.modal('hide');
                location.reload();
              }
            },
            error: (response) =>{
              form.html(response);
            }
          })
        });
        document.body.classList.add("dark")
      });
</script>
<style>
    .error {
        border: 1px solid red !important;
    }

    .error-text {
        color: red !important;
        font-size: 12px !important;
    }
  </style>

app/dashboard/templates/includes/sidebar.html
<!-- [ navigation menu ] start -->
<nav class="pcoded-navbar">
    <div class="navbar-wrapper">
        <div class="navbar-brand header-logo">
            <a href="{% url 'dashboard:index' %}" class="b-brand">
                <div class="b-bg">
                    <i class="feather icon-trending-up"></i>
                </div>
                <span class="b-title">{{ _("Dashboard") }}</span>
            </a>
            <a class="mobile-menu" id="mobile-collapse" href="{% url 'dashboard:index' %}"><span></span></a>
        </div>
        <div class="navbar-content scroll-div">
            <ul class="nav pcoded-inner-navbar">
                <li class="nav-item pcoded-menu-caption">
                    <label>{{ _("Navigation") }}</label>
                </li>
                <li data-username="User Dashboard Page" 
                    class="nav-item {% if 'dashboard:index' in segment %} active {% endif %}">
                    <a href="{% url 'dashboard:index' %}" class="nav-link">
                        <span class="pcoded-micon"><i class="feather icon-shop"></i></span>
                            <span class="pcoded-mtext">{{ _("Welcome") }}</span></a>
                </li>
                <li data-username="Profile Dashboard Page" 
                    class="nav-item {% if 'dashboard:profile' in segment %} active {% endif %}">
                    <a href="{% url 'dashboard:profile' %}" class="nav-link">
                        <span class="pcoded-micon"><i class="feather icon-shop"></i></span>
                            <span class="pcoded-mtext">{{ _("Profile") }}</span></a>
                </li>
                <li data-username="Profile Dashboard Page" 
                    class="nav-item {% if 'storage_drive' in segment %} active {% endif %}">
                    <a href="{% url 'storage_drive:list' %}" class="nav-link">
                        <span class="pcoded-micon"><i class="feather icon-shop"></i></span>
                            <span class="pcoded-mtext">{{ _("Storage") }}</span></a>
                </li>

                <li class="nav-item pcoded-menu-caption">
                    <label>{{ _("Tables") }}</label>
                </li>
                <li data-username="User Dashboard Page" 
                    class="nav-item {% if 'user_index' in segment %} active {% endif %}">
                    <a href="{% url 'dashboard:user_index' %}" class="nav-link">
                        <span class="pcoded-micon"><i class="feather icon-shop"></i></span>
                            <span class="pcoded-mtext">{{ _("Users") }}</span></a>
                </li>

                <li class="nav-item pcoded-menu-caption">
                    <label>{{ _("Server list") }}</label>
                </li>
                {% for server in servers %}
                    <li data-username="Charts Morris" 
                        class="nav-item {% if server in segment %}active{% endif %}">
                        <a href="{% url 'dashboard:servers' server=server %}" class="nav-link "><span
                            class="pcoded-micon"><i class="feather icon-pie-chart"></i></span><span class="pcoded-mtext">{{ server }}</span></a>
                    </li>
                {% endfor %}
                <li class="nav-item pcoded-menu-caption">
                    <label>{{ _("Action") }}</label>
                </li>


                <li data-username="Disabled Menu" class="nav-item">
                    <a href="{% url 'dashboard_auth:logout' %}" class="nav-link">
                        <span class="pcoded-micon"><i class="feather icon-power"></i></span><span class="pcoded-mtext">{{ _("Logout") }}</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- [ navigation menu ] end -->