app/dashboard/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path, include
from dashboard import views
 

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile', views.profile, name='profile'),
    path('user',include('dashboard.tables.user.urls')),
    path('servers/<str:server>', views.servers, name='servers'),
]

app/dashboard_authentication/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import login_view, register_user
from django.contrib.auth.views import LogoutView

app_name='dashboard_auth'

urlpatterns = [
     path('login', login_view, name="login"), 
     path('register', register_user, name="register"),
     path("logout", LogoutView.as_view(), name="logout"),
]

app/monitoring/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect, render
from django.urls import reverse

def redirect_to_dashboard(request):
    return redirect(reverse('dashboard:index'))

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/auth/', include('dashboard_authentication.urls',namespace='dashboard_auth')),
    path('dashboard/', include('dashboard.urls',namespace='dashboard')),
    path('dashboard/drive/', include('storage_drive.urls',namespace='storage_drive')),
    path('api/dashboard/', include('dashboard_api.urls',namespace='dashboard_api')),
    path('', redirect_to_dashboard)
]

def page_not_found_view(request, exception):
    return render(request, 'dashboard/page-404.html', status=404)

handler404 = page_not_found_view

#if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/dashboard_authentication/models.py
from django.db import models

# Create your models here.

app/dashboard_authentication/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from dashboard.models import CustomUser


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))


class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Email",
                "class": "form-control"
            }
        ))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password check",
                "class": "form-control"
            }
        ))

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')

app/dashboard_authentication/views.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

# Create your views here.
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login
from .forms import LoginForm, SignUpForm
#from backend.settings import GITHUB_AUTH
GITHUB_AUTH = False

def login_view(request):
    form = LoginForm(request.POST or None)

    msg = None

    if request.method == "POST":

        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse('dashboard:index'))
            else:
                msg = 'Invalid credentials'
        else:
            msg = 'Error validating the form'

    return render(request, "accounts/login.html", {"form": form, "msg": msg, "GITHUB_AUTH": GITHUB_AUTH})


def register_user(request):
    msg = None
    success = False

    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)

            msg = 'User created successfully.'
            success = True

            # return redirect("/login/")

        else:
            msg = 'Form is not valid'
    else:
        form = SignUpForm()

    return render(request, "accounts/register.html", {"form": form, "msg": msg, "success": success})

app/dashboard_authentication/templates/accounts/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %}

{% block content %}   

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">

                    <h3 class="mb-4">{{ _("Login") }}</h3>

                    <span class="mb-0 text-muted">
                        {% if msg %}
                            <span class="text-danger">{{ msg | safe }}</span>
                        {% else %}
                            Add your credentials
                        {% endif %} 
                    </span>

                    <br />
                    <br />

                    <form role="form" method="post" action="">

                        {% csrf_token %}                   

                        <div class="input-group mb-3">
                            {{ form.username }}
                        </div>
                        
                        <div class="input-group mb-4">
                            {{ form.password }}
                        </div>
                        
                        <button type="submit" name="login" class="btn btn-primary shadow-2 mb-4">{{ _("Login") }}</button>

                    </form>

                    <p class="mb-0 text-muted">Don’t have an account? <a href="{% url 'dashboard_auth:register' %}" >{{ _("Sign Up") }}</a></p>

                    <br />   

                </div>
            </div>
        </div>
    </div>

{% endblock content %}

app/dashboard_authentication/templates/accounts/register.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %}

{% block content %}   

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <i class="feather icon-user-plus auth-icon"></i>
                    </div>
                    <h3 class="mb-4">{{ _("Sign Up") }}</h3>

                    <span class="mb-0 text-muted">
                        {% if msg %}
                            <span class="text-danger">{{ msg | safe }}</span>
                        {% else %}
                            Add your credentials
                        {% endif %} 
                    </span>

                    <br />
                    <br />

                    <!-- Hide the form on success -->
                    {% if success %}

                        <a href="{% url 'dashboard_auth:login' %}" class="btn btn-primary shadow-2 mb-4">Sign IN</a>

                    {% else %}

                        <form role="form" method="post" action="">

                            {% csrf_token %}                    

                            <div class="input-group mb-3">
                                {{ form.username }}
                            </div>
                            <span class="text-error">{{ form.username.errors }}</span>

                            <div class="input-group mb-3">
                                {{ form.email }}
                            </div>
                            <span class="text-error">{{ form.email.errors }}</span>

                            <div class="input-group mb-4">
                                {{ form.password1 }}
                            </div>
                            <span class="text-error">{{ form.password1.errors }}</span>

                            <div class="input-group mb-4">
                                {{ form.password2 }}
                            </div>
                            <span class="text-error">{{ form.password2.errors }}</span>
                            
                            <button type="submit" name="register" class="btn btn-primary shadow-2 mb-4">{{ _("Sign Up") }}</button>

                        </form>

                        <p class="mb-0 text-muted">Already have an account? <a href="{% url 'dashboard_auth:login' %}" >{{ _("Login") }}</a></p>
                    
                    {% endif %}

                </div>
            </div>
        </div>
    </div>

{% endblock content %}